version: "3"

services:
  bankcsv-rompslomp:
    container_name: bankcsv-rompslomp
    image: ghcr.io/terrorsource/bankcsv-rompslomp:latest
    init: true
    restart: unless-stopped
    network_mode: bridge
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - 8321:8000
    volumes:
      - /share/CACHEDEV1_DATA/Docker/bankcsv-rompslomp:/data
